// <auto-generated />
using System;
using LIBRARY_MANAGEMENT_SYSTEM__LMS_.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LIBRARY_MANAGEMENT_SYSTEM__LMS_.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924223015_initi")]
    partial class initi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LIBRARY_MANAGEMENT_SYSTEM__LMS_.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Robert Martin",
                            AvailableCopies = 5,
                            CategoryId = 1,
                            Price = 45.99m,
                            PublishedYear = 2008,
                            Title = "Clean Code"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "David Thomas",
                            AvailableCopies = 3,
                            CategoryId = 1,
                            Price = 39.99m,
                            PublishedYear = 1999,
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "George Orwell",
                            AvailableCopies = 7,
                            CategoryId = 2,
                            Price = 25.50m,
                            PublishedYear = 1949,
                            Title = "1984"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "James Clear",
                            AvailableCopies = 10,
                            CategoryId = 4,
                            Price = 30.00m,
                            PublishedYear = 2018,
                            Title = "Atomic Habits"
                        });
                });

            modelBuilder.Entity("LIBRARY_MANAGEMENT_SYSTEM__LMS_.Models.BorrowRecord", b =>
                {
                    b.Property<int>("BorrowRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BorrowRecordId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BorrowDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BorrowRecordId");

                    b.HasIndex("BookId");

                    b.HasIndex("MemberId");

                    b.ToTable("BorrowRecords");

                    b.HasData(
                        new
                        {
                            BorrowRecordId = 1,
                            BookId = 1,
                            BorrowDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 1,
                            ReturnDate = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowRecordId = 2,
                            BookId = 2,
                            BorrowDate = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 2
                        },
                        new
                        {
                            BorrowRecordId = 3,
                            BookId = 3,
                            BorrowDate = new DateTime(2026, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 1,
                            ReturnDate = new DateTime(2026, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BorrowRecordId = 4,
                            BookId = 4,
                            BorrowDate = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 3
                        });
                });

            modelBuilder.Entity("LIBRARY_MANAGEMENT_SYSTEM__LMS_.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Programming"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "History"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Self Development"
                        });
                });

            modelBuilder.Entity("LIBRARY_MANAGEMENT_SYSTEM__LMS_.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MemberId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberId = 1,
                            Email = "ahmed@example.com",
                            FullName = "Ahmed Hassan",
                            PhoneNumber = "01012345678"
                        },
                        new
                        {
                            MemberId = 2,
                            Email = "sara@example.com",
                            FullName = "Sara Mohamed",
                            PhoneNumber = "01123456789"
                        },
                        new
                        {
                            MemberId = 3,
                            Email = "omar@example.com",
                            FullName = "Omar Ali"
                        });
                });

            modelBuilder.Entity("LIBRARY_MANAGEMENT_SYSTEM__LMS_.Models.Book", b =>
                {
                    b.HasOne("LIBRARY_MANAGEMENT_SYSTEM__LMS_.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LIBRARY_MANAGEMENT_SYSTEM__LMS_.Models.BorrowRecord", b =>
                {
                    b.HasOne("LIBRARY_MANAGEMENT_SYSTEM__LMS_.Models.Book", "Book")
                        .WithMany("BorrowRecords")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LIBRARY_MANAGEMENT_SYSTEM__LMS_.Models.Member", "Member")
                        .WithMany("BorrowRecords")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LIBRARY_MANAGEMENT_SYSTEM__LMS_.Models.Book", b =>
                {
                    b.Navigation("BorrowRecords");
                });

            modelBuilder.Entity("LIBRARY_MANAGEMENT_SYSTEM__LMS_.Models.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LIBRARY_MANAGEMENT_SYSTEM__LMS_.Models.Member", b =>
                {
                    b.Navigation("BorrowRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
